[build]
  functions = "functions"  # The folder containing your serverless function (flask.py)
  publish = "static"       # Folder containing static assets (if any)

[context.production.environment]
  FLASK_APP = "functions/flask_app.py"
